spring:
  application:
    name: lpg-service
  datasource:
    url: jdbc:h2:mem:lpg-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /